<a href="https://colab.research.google.com/github/Deepanshu-yt/python/blob/main/Day6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#file handling -> direct access without drive

data = open("file upload.csv","r")
data.read()

'name,roll no\ndheeraj,123\nkunal,1234\nabhishek,12345\npraveen,12356\nanjali,1234567'

In [3]:
#direct access csv file
data1 = open("file upload.csv","r")
data1.read()


'name,roll no\ndheeraj,123\nkunal,1234\nabhishek,12345\npraveen,12356\nanjali,1234567'

In [9]:
# Numpy
# !pip install numpy
import numpy as np
#id
l = [10,20,30]
l*2

# power of numpy
arr = np.array(l)
arr
arr*2

array([20, 40, 60])

In [10]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)
print(arr[0])
print(arr[-1])

[1 2 3 4]
1
4


In [11]:
import numpy as np
#check type
l = [12,13,14,15]
print(l)
print(type(l))



[12, 13, 14, 15]
<class 'list'>


In [16]:
#change values
import numpy as np
l = [10,20,30]
l[0] = 100

print(l)
# numpy
arr = np.array(l)
arr[0] = 100
arr[-1] = 200
print(arr)

[100, 20, 30]
[100  20 200]


In [20]:
#value add = 2
import numpy as np

l = [10,20,30,40]
# print(l+2) # add not acceptable with list

arr = np.array(l)
print(arr+2)

[12 22 32 42]


In [24]:
for i in range(5):
  print(i)

0
1
2
3
4


In [30]:
# arange in numpy
import numpy as np
arr = np.arange(5) # start,stop,jump
print(arr)

arr = np.arange(1,20,2)
print(arr)

[0 1 2 3 4]
[ 1  3  5  7  9 11 13 15 17 19]


In [32]:
# SIMPLE 2D EX
import numpy as np
print("list start")
l = [[1,2,3],[4,5,6]]
print(l)
print("numpy start")
#numpy 2d
arr = np.array(l)
print(arr)

list start
[[1, 2, 3], [4, 5, 6]]
numpy start
[[1 2 3]
 [4 5 6]]
