<a href="https://colab.research.google.com/github/Deepanshu-yt/python/blob/main/Day7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([10,20,30,6,3,2])
arr_f = arr[arr != 6]
print(arr_f)

# example and opr 10 se 20 between
arr1 = np.array([5,6,7,8,11,24,16,19,25])
arr_f1 = arr1[(arr1>10) & (arr1<20)]
print(arr_f1)


[10 20 30  3  2]
[11 16 19]


In [ ]:
import numpy as np
arr = np.array([10,15,20,19,30])
arr_f = arr[(arr > 10) & (arr < 20)]
print(arr_f)


[15 19]


In [ ]:
arr = np.array([15, 20, 5, 6,12, 18, 9])

arr_f = np.where((arr > 10) & (arr < 20), arr * 2, arr + 10)

print(arr_f)


[30 30 15 16 24 36 19]


In [ ]:
arr1 = np.array([[10, 20, 30],

                 [40, 50, 60]])

arr2 = np.array([[1, 2, 3],

                 [4, 5, 6]])

arr1_arr2 = np.concatenate((arr1, arr2), axis=0)

print(arr1_arr2)


[[10 20 30]
 [40 50 60]
 [ 1  2  3]
 [ 4  5  6]]


In [ ]:
import numpy as np
from scipy import stats

arr = np.array([2,2,3,4,4,4,5])

result = stats.mode(arr)

print("Mode :", result.mode)
print("Frequency :", result.count)

Mode : 4
Frequency : 3
